### ISSUE TITLE
Issues này có kèm theo ảnh nhằm thử xem Kode Feeds có xử lí tốt không

### ISSUE THREAD

**Issue by quocthinhvo** [kodestudio/kodestudio.github.io#5]
![46624702](https://user-images.githubusercontent.com/46624702/90159602-d840c380-ddba-11ea-93bc-d61b298456f9.png =100%x*)

**Comment by th1nhhdk** [comment]
![46624702](https://user-images.githubusercontent.com/46624702/90159602-d840c380-ddba-11ea-93bc-d61b298456f9.png)
Bỏ "=100%x*" ở cuối link ra

**Comment by th1nhhdk** [comment]
Nên close cái này :))
